/**
 * Generates public/sw.js with an embedded build version.
 * Run automatically via `prebuild` so every deploy gets a unique SW.
 */
import fs from 'fs';
import path from 'path';
import { fileURLToPath } from 'url';

const __dirname = path.dirname(fileURLToPath(import.meta.url));
const root = path.join(__dirname, '..');

const pkg = JSON.parse(fs.readFileSync(path.join(root, 'package.json'), 'utf8'));

const buildId =
  process.env.NEXT_PUBLIC_SW_VERSION ||
  process.env.VERCEL_GIT_COMMIT_SHA?.slice(0, 12) ||
  process.env.GITHUB_SHA?.slice(0, 12) ||
  `${pkg.version || '1.0.0'}-${Date.now()}`;

const SW_VERSION = `juco-cafe-v${buildId}`.replace(/[^a-zA-Z0-9._-]/g, '-');

const swSource = `// AUTO-GENERATED by scripts/generate-sw.mjs — do not edit manually
const SW_VERSION = "${SW_VERSION}";
const STATIC_CACHE = "juco-static-" + SW_VERSION;
const SHELL_CACHE = "juco-shell-" + SW_VERSION;
const RUNTIME_CACHE = "juco-runtime-" + SW_VERSION;

const PRECACHE_URLS = [
  "/manifest.json",
  "/icon-192.png",
  "/icon-512.png",
  "/offline.html",
];

const STATIC_ASSET_RE = /\\.(png|jpg|jpeg|gif|webp|svg|ico|woff2?|ttf|otf)$/i;
const AUDIO_EXT_RE = /\\.(mp3|wav|ogg|m4a|aac)$/i;

function shouldBypassServiceWorker(request, url) {
  if (AUDIO_EXT_RE.test(url.pathname)) return true;
  if (request.headers.has("range")) return true;
  return false;
}

function shouldIgnoreRequest(request, url) {
  if (request.method !== "GET") return true;

  const protocol = url.protocol;
  if (protocol === "chrome-extension:" || protocol === "browser-extension:") return true;
  if (protocol === "ws:" || protocol === "wss:") return true;

  return false;
}

function isNavigation(request, url) {
  return request.mode === "navigate" || url.pathname.startsWith("/driver");
}

function isApiRequest(url) {
  return url.pathname.startsWith("/api/");
}

function isAppBundle(url) {
  return url.pathname.startsWith("/_next/");
}

function isCriticalAppPath(url) {
  return (
    url.pathname.startsWith("/driver") ||
    url.pathname.startsWith("/track") ||
    url.pathname.startsWith("/admin") ||
    url.pathname.startsWith("/order-success")
  );
}

function isStaticAsset(url) {
  if (url.pathname.startsWith("/_next/static/media/")) return true;
  return STATIC_ASSET_RE.test(url.pathname);
}

function offlineResponse() {
  return new Response("Offline", {
    status: 503,
    headers: { "Content-Type": "text/plain" },
  });
}

/** Cache API rejects 206 Partial Content and most non-200 responses. */
function isCacheableResponse(response) {
  if (!response) return false;
  if (response.status === 206) return false;
  if (response.status === 200) return true;
  if (response.type === "opaque") return true;
  return false;
}

function putInCache(cache, request, response) {
  if (!isCacheableResponse(response)) return;
  void cache.put(request, response.clone()).catch(() => undefined);
}

async function navigationFallback() {
  const offline = await caches.match("/offline.html");
  if (offline) return offline;
  return offlineResponse();
}

async function navigationCacheFirst(request) {
  const cache = await caches.open(SHELL_CACHE);
  try {
    const response = await fetch(request);
    if (response) {
      putInCache(cache, request, response);
    }
    return response;
  } catch (err) {
    const cached = await cache.match(request);
    if (cached) return cached;
    return navigationFallback();
  }
}

async function networkFirst(request) {
  const cache = await caches.open(RUNTIME_CACHE);
  try {
    const response = await fetch(request);
    putInCache(cache, request, response);
    return response;
  } catch (err) {
    const cached = await caches.match(request);

    if (cached) {
      return cached;
    }

    if (request.mode === "navigate") {
      return navigationFallback();
    }

    return offlineResponse();
  }
}

async function cacheFirst(request) {
  const cached = await caches.match(request);
  if (cached) return cached;

  try {
    const response = await fetch(request);
    if (response) {
      const cache = await caches.open(STATIC_CACHE);
      putInCache(cache, request, response);
    }
    return response;
  } catch (err) {
    const fallback = await caches.match(request);
    if (fallback) return fallback;
    return offlineResponse();
  }
}

self.addEventListener("install", (event) => {
  self.skipWaiting();
  event.waitUntil(
    caches.open(STATIC_CACHE).then((cache) =>
      cache.addAll(PRECACHE_URLS).catch(() => undefined)
    )
  );
});

self.addEventListener("activate", (event) => {
  event.waitUntil(
    (async () => {
      const keys = await caches.keys();
      const keep = [STATIC_CACHE, SHELL_CACHE, RUNTIME_CACHE];
      await Promise.all(
        keys.filter((key) => !keep.includes(key)).map((key) => caches.delete(key))
      );
      await self.clients.claim();
    })()
  );
});

self.addEventListener("message", (event) => {
  if (event.data?.type === "SKIP_WAITING") {
    self.skipWaiting();
  }
});

self.addEventListener("fetch", (event) => {
  const { request } = event;
  const url = new URL(request.url);

  if (shouldIgnoreRequest(request, url)) return;

  if (url.origin !== self.location.origin) return;

  if (shouldBypassServiceWorker(request, url)) return;

  if (isNavigation(request, url)) {
    event.respondWith(navigationCacheFirst(request));
    return;
  }

  if (isApiRequest(url) || isAppBundle(url) || isCriticalAppPath(url)) {
    event.respondWith(networkFirst(request));
    return;
  }

  if (isStaticAsset(url)) {
    event.respondWith(cacheFirst(request));
    return;
  }

  event.respondWith(networkFirst(request));
});
`;

const outPath = path.join(root, 'public', 'sw.js');
fs.writeFileSync(outPath, swSource, 'utf8');

const envPath = path.join(root, '.env.sw-version');
fs.writeFileSync(envPath, `NEXT_PUBLIC_SW_VERSION=${SW_VERSION}\n`, 'utf8');

console.log(`[generate-sw] Wrote ${outPath} (${SW_VERSION})`);
